// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return windows;
      case TargetPlatform.iOS:
        return macos;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvcufcczWMWTWD9gtvpPEj0l3OAYru-ew',
    appId: '1:559509235392:ios:819aff64d375b6fb186f25',
    messagingSenderId: '559509235392',
    projectId: 'codechef-779c2',
    storageBucket: 'codechef-779c2.firebasestorage.app',
    iosBundleId: 'com.example.codepath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC99acqH_0y2M3CaqwZMePsF10_8gf9e2I',
    appId: '1:559509235392:web:9bbfd91216f83d4f186f25',
    messagingSenderId: '559509235392',
    projectId: 'codechef-779c2',
    authDomain: 'codechef-779c2.firebaseapp.com',
    storageBucket: 'codechef-779c2.firebasestorage.app',
    measurementId: 'G-ZQDEV5P363',
  );
}
